apiVersion: v1
kind: ConfigMap
metadata:
  name: last9-k8s-infra-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "last9.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  LAST9_OTLP_ENDPOINT: {{ required "last9.otlpEndpoint required" .Values.last9.otlpEndpoint | quote }}
  LAST9_CLUSTER_NAME: {{ required "last9.cluster.name required" .Values.last9.cluster.name | quote }}
  LAST9_ENVIRONMENT: {{ .Values.last9.environment | default "production" | quote }}
