{{- if and (not .Values.last9.existingSecret) .Values.last9.writeToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "last9.fullname" . }}-otlp-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "last9.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  authorization: {{ .Values.last9.writeToken | quote }}
{{- end }}
